dependencies:
  - python=3.11
  - fastapi>=0.68.0
  - uvicorn>=0.15.0
  - sqlalchemy>=1.4.23
  - pydantic>=1.8.2
  - python-dotenv>=0.19.0
  - pandas>=1.3.3
  - pytest>=6.2.5
  - httpx>=0.23.0
  - python-multipart>=0.0.5
  - openpyxl>=3.0.0 
  - pip
  - pip:
    - pro-football-reference-web-scraper>=0.1.0