dependencies:
  - python=3.11
  - fastapi>=0.68.0
  - uvicorn>=0.15.0
  - sqlalchemy>=1.4.23
  - pydantic>=1.8.2
  - python-dotenv>=0.19.0
  - pandas>=1.3.3
  - pytest>=6.2.5
  - httpx>=0.23.0
  - python-multipart>=0.0.5
  - openpyxl>=3.0.0
  - aiohttp>=3.8.0
  - beautifulsoup4>=4.10.0
  - pip
  - pip:
    - nfl-data-py>=0.3.0
    - pytest-asyncio>=0.16.0